[package]
name = "asm"
version = "0.1.0"
edition = "2021"

[build-dependencies] 
lalrpop = "0.22.0"

[dependencies]
nom = "7.1.3"
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }