use std::str::FromStr;
use crate::ast::{Expr, BinaryOp, UnaryOp, TernaryOp};

grammar;

pub Expr: Box<Expr> = {
    Num => Box::new(Expr::Num(<>)),
    Id => Box::new(Expr::Id(<>)),
    "true" => Box::new(Expr::Bool(true)),
    "false" => Box::new(Expr::Bool(false)),
    "()" => Box::new(Expr::Unit),
    "(" <op:UnPrim> <e:Expr> ")" => Box::new(Expr::UnOp(op, e)),
    "(" <op:BinPrim> <e1:Expr> <e2:Expr> ")" => Box::new(Expr::BinOp(op, e1, e2)),
    "(" <op:TriPrim> <e1:Expr> <e2:Expr> <e3:Expr> ")" => Box::new(Expr::TriOp(op, e1, e2, e3)),
    "(" "if" <cond:Expr> <then:Expr> <else_:Expr> ")" => Box::new(Expr::If(cond, then, else_)),
    "(" "let" "(" <bindings:Bindings> ")" <body:Expr> ")" => Box::new(Expr::Let(bindings, body)),
    "(" "do" <exprs:Expr+> ")" => Box::new(Expr::Do(exprs)),
}

Bindings: Vec<(String, Box<Expr>)> = {
    "(" <name:Id> <expr:Expr> ")" => vec![(name, expr)],
    <mut bindings:Bindings> "(" <name:Id> <expr:Expr> ")" => {
        bindings.push((name, expr));
        bindings
    },
};

UnPrim: UnaryOp = {
    "add1" => UnaryOp::Add1,
    "sub1" => UnaryOp::Sub1,
    "zero?" => UnaryOp::IsZero,
    "num?" => UnaryOp::IsNum,
    "not" => UnaryOp::Not,
    "pair?" => UnaryOp::IsPair,
    "left" => UnaryOp::Left,
    "right" => UnaryOp::Right,
    "list?" => UnaryOp::IsList,
    "vector?" => UnaryOp::IsVector,
    "vector-length" => UnaryOp::VectorLength,
};

BinPrim: BinaryOp = {
    "+" => BinaryOp::Add,
    "-" => BinaryOp::Sub,
    "=" => BinaryOp::Eq,
    "<" => BinaryOp::Lt,
    "pair" => BinaryOp::Pair,
    "vector" => BinaryOp::Vector,
    "vector-get" => BinaryOp::VectorGet,
};

TriPrim: TernaryOp = {
    "vector-set" => TernaryOp::VectorSet,
};

Num: i64 = {
    r"-?[0-9]+" => i64::from_str(<>).unwrap(),
};

Id: String = {
    r"[a-zA-Z][a-zA-Z0-9_-]*" => <>.to_string(),
};