use std::str::FromStr;
use crate::ast::{Expr, BinaryOp, UnaryOp, TernaryOp, Definition, Program, TopLevelItem};

grammar;

pub Program: Program = {
    <exps:TopLevel+> => {
        let mut defs = Vec::new();
        let mut expr = None;
        for exp in exps {
            match exp {
                TopLevelItem::Def(def) => defs.push(def),
                TopLevelItem::Expr(e) => {
                    if expr.is_none() {
                        expr = Some(e);
                    } else {
                        // If we already have an expression, wrap everything in a Do
                        let prev = expr.unwrap();
                        expr = Some(Box::new(Expr::Do(vec![prev, e])));
                    }
                }
            }
        }
        Program(defs, *expr.unwrap_or(Box::new(Expr::Unit)))
    }
};

pub TopLevel: TopLevelItem = {
    Definition => TopLevelItem::Def(<>),
    Expr => TopLevelItem::Expr(<>),
};

pub Definition: Definition = {
    "(" "define" "(" <name:Id> <params:Id*> ")" <body:Expr> ")" => 
        Definition(name, params, *body),
};

pub Expr: Box<Expr> = {
    Num => Box::new(Expr::Num(<>)),
    Id => Box::new(Expr::Id(<>)),
    "true" => Box::new(Expr::Bool(true)),
    "false" => Box::new(Expr::Bool(false)),
    "()" => Box::new(Expr::Unit),
    "(" <op:UnPrim> <e:Expr> ")" => Box::new(Expr::UnOp(op, e)),
    "(" <op:BinPrim> <e1:Expr> <e2:Expr> ")" => Box::new(Expr::BinOp(op, e1, e2)),
    "(" <op:TriPrim> <e1:Expr> <e2:Expr> <e3:Expr> ")" => Box::new(Expr::TriOp(op, e1, e2, e3)),
    "(" "if" <cond:Expr> <then:Expr> <else_:Expr> ")" => Box::new(Expr::If(cond, then, else_)),
    "(" "let" "(" <bindings:Bindings> ")" <body:Expr> ")" => Box::new(Expr::Let(bindings, body)),
    "(" "do" <exprs:Expr+> ")" => Box::new(Expr::Do(exprs)),
    "(" <name:Id> <args:Expr*> ")" => Box::new(Expr::Call(name, args)),
};


Bindings: Vec<(String, Box<Expr>)> = {
    "(" <name:Id> <expr:Expr> ")" => vec![(name, expr)],
    <mut bindings:Bindings> "(" <name:Id> <expr:Expr> ")" => {
        bindings.push((name, expr));
        bindings
    },
};

UnPrim: UnaryOp = {
    "add1" => UnaryOp::Add1,
    "sub1" => UnaryOp::Sub1,
    "zero?" => UnaryOp::IsZero,
    "num?" => UnaryOp::IsNum,
    "not" => UnaryOp::Not,
    "pair?" => UnaryOp::IsPair,
    "left" => UnaryOp::Left,
    "right" => UnaryOp::Right,
    "list?" => UnaryOp::IsList,
    "vector?" => UnaryOp::IsVector,
    "vector-length" => UnaryOp::VectorLength,
};

BinPrim: BinaryOp = {
    "+" => BinaryOp::Add,
    "-" => BinaryOp::Sub,
    "=" => BinaryOp::Eq,
    "<" => BinaryOp::Lt,
    "pair" => BinaryOp::Pair,
    "vector" => BinaryOp::Vector,
    "vector-get" => BinaryOp::VectorGet,
};

TriPrim: TernaryOp = {
    "vector-set" => TernaryOp::VectorSet,
};

Num: i64 = {
    r"-?[0-9]+" => i64::from_str(<>).unwrap(),
};

Id: String = {
    r"[a-zA-Z][a-zA-Z0-9_-]*" => <>.to_string(),
};
